// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/entrypoint.proto

package entrypoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level     string `protobuf:"bytes,1,opt,name=Level,proto3" json:"Level,omitempty"`
	Prefix    string `protobuf:"bytes,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Lang      string `protobuf:"bytes,4,opt,name=Lang,proto3" json:"Lang,omitempty"`
	UserAgent string `protobuf:"bytes,5,opt,name=UserAgent,proto3" json:"UserAgent,omitempty"`
	Trace     string `protobuf:"bytes,6,opt,name=Trace,proto3" json:"Trace,omitempty"`
	IP        string `protobuf:"bytes,7,opt,name=IP,proto3" json:"IP,omitempty"`
	Time      string `protobuf:"bytes,8,opt,name=Time,proto3" json:"Time,omitempty"`
	Token     string `protobuf:"bytes,9,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *PayloadRequest) Reset() {
	*x = PayloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entrypoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRequest) ProtoMessage() {}

func (x *PayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entrypoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRequest.ProtoReflect.Descriptor instead.
func (*PayloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_entrypoint_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PayloadRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PayloadRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PayloadRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *PayloadRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PayloadRequest) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *PayloadRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *PayloadRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *PayloadRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PayloadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PayloadReply) Reset() {
	*x = PayloadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entrypoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadReply) ProtoMessage() {}

func (x *PayloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entrypoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadReply.ProtoReflect.Descriptor instead.
func (*PayloadReply) Descriptor() ([]byte, []int) {
	return file_proto_entrypoint_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_entrypoint_proto protoreflect.FileDescriptor

var file_proto_entrypoint_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xda,
	0x01, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x61, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x1c, 0x0a,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x50, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28, 0x0a, 0x0c, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x85, 0x01, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x67,
	0x53, 0x79, 0x6e, 0x63, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x41, 0x73, 0x79, 0x6e,
	0x63, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a,
	0x0f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_entrypoint_proto_rawDescOnce sync.Once
	file_proto_entrypoint_proto_rawDescData = file_proto_entrypoint_proto_rawDesc
)

func file_proto_entrypoint_proto_rawDescGZIP() []byte {
	file_proto_entrypoint_proto_rawDescOnce.Do(func() {
		file_proto_entrypoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_entrypoint_proto_rawDescData)
	})
	return file_proto_entrypoint_proto_rawDescData
}

var file_proto_entrypoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_entrypoint_proto_goTypes = []interface{}{
	(*PayloadRequest)(nil), // 0: grpc.PayloadRequest
	(*PayloadReply)(nil),   // 1: grpc.PayloadReply
}
var file_proto_entrypoint_proto_depIdxs = []int32{
	0, // 0: grpc.Entrypoint.WriteLogSync:input_type -> grpc.PayloadRequest
	0, // 1: grpc.Entrypoint.WriteLogAsync:input_type -> grpc.PayloadRequest
	1, // 2: grpc.Entrypoint.WriteLogSync:output_type -> grpc.PayloadReply
	1, // 3: grpc.Entrypoint.WriteLogAsync:output_type -> grpc.PayloadReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_entrypoint_proto_init() }
func file_proto_entrypoint_proto_init() {
	if File_proto_entrypoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_entrypoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_entrypoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_entrypoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_entrypoint_proto_goTypes,
		DependencyIndexes: file_proto_entrypoint_proto_depIdxs,
		MessageInfos:      file_proto_entrypoint_proto_msgTypes,
	}.Build()
	File_proto_entrypoint_proto = out.File
	file_proto_entrypoint_proto_rawDesc = nil
	file_proto_entrypoint_proto_goTypes = nil
	file_proto_entrypoint_proto_depIdxs = nil
}
